language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-user-node-udacity --build-arg POSTGRES_USERNAME=${ARG POSTGRES_USERNAME} --build-arg POSTGRES_PASSWORD=${ARG POSTGRES_PASSWORD} --build-arg POSTGRES_HOST=${ARG POSTGRES_HOST} --build-arg POSTGRES_DB=${ARG POSTGRES_DB} --build-arg AWS_BUCKET=${ARG AWS_BUCKET} --build-arg AWS_REGION=${ARG AWS_REGION} --build-arg AWS_PROFILE=${ARG AWS_PROFILE} --build-arg JWT_SECRET=${ARG JWT_SECRET} --build-arg URL=${ARG URL} .
  - docker images
  - docker tag udagram-user-node-udacity ta9i/udagram-user-node-udacity

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ta9i/udagram-user-node-udacity