language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-user-node-udacity  --build-arg POSTGRES_USERNAME=${argPOSTGRES_USERNAME} --build-arg POSTGRES_PASSWORD=${argPOSTGRES_PASSWORD} --build-arg POSTGRES_HOST=${argPOSTGRES_HOST} --build-arg POSTGRES_DB=${argPOSTGRES_DB} --build-arg AWS_BUCKET=${argAWS_BUCKET} --build-arg AWS_REGION=${argAWS_REGION} --build-arg AWS_PROFILE=${argAWS_PROFILE} --build-arg JWT_SECRET=${argJWT_SECRET} --build-arg URL=${argURL} .
 .
  - docker images
  - docker tag udagram-user-node-udacity ta9i/udagram-user-node-udacity

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ta9i/udagram-user-node-udacity