language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-user-node-udacity  --build-arg argPOSTGRES_USERNAME=${POSTGRES_USERNAME} --build-arg argPOSTGRES_PASSWORD=${POSTGRES_PASSWORD} --build-arg argPOSTGRES_HOST=${POSTGRES_HOST} --build-arg argPOSTGRES_DB=${POSTGRES_DB} --build-arg argAWS_BUCKET=${AWS_BUCKET} --build-arg argAWS_REGION=${AWS_REGION} --build-arg argAWS_PROFILE=${AWS_PROFILE} --build-arg argJWT_SECRET=${JWT_SECRET} --build-arg argURL=${URL} .
  - docker images
  - docker tag udagram-user-node-udacity ta9i/udagram-user-node-udacity

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ta9i/udagram-user-node-udacity