apiVersion: v1
kind: Service
metadata:
  name: udagram-user-node-udacity
  labels:
    run: udagram-user-node-udacity
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: udagram-user-node-udacity